[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
fushuma = "https://rpc.fushuma.com"

[etherscan]
fushuma = { key = "${FUSHUMA_EXPLORER_API_KEY}", url = "https://explorer.fushuma.com/api" }
