[profile.default]
src = "src/infinity-core"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/",
    "infinity-core/=src/infinity-core/",
    "permit2/=lib/permit2/",
    "pancake-create3-factory/=lib/pancake-create3-factory/"
]

[profile.governance]
src = "contracts"
solc_version = "0.8.19"
evm_version = "paris"
optimizer_runs = 200

[rpc_endpoints]
fushuma = "https://rpc.fushuma.com"

[etherscan]
fushuma = { key = "${FUSHUMA_EXPLORER_API_KEY}", url = "https://explorer.fushuma.com/api" }
